### ISSUE TITLE
Next alarm always showing as January 1, 1970, 12:00 AM

### ISSUE THREAD

**Issue by sikaiser** [Johboh/hassalarm#24]
I just set it up the first time, and feel like I did everything correctly according to the readme, but I'm not getting the proper alarm time and date in home assistant.

![grafik](https://user-images.githubusercontent.com/17196288/103772983-a90d4600-502a-11eb-87ac-2d71e138b41c.png)

My `configuration.yaml`

```
# Sensors
sensor:
  - platform: time_date # for Hassalarm
    display_options:
      - 'date_time'

# For Hassalarm
input_datetime:
  next_alarm:
    name: Nächster Wecker
    has_date: true
    has_time: true
```

My `automations.yaml` (for webhook).
Note, I haven't created any automation to use the alarm yet.

```
- id: 'hassalarm'
  alias: Webhook for Hassalarm
  trigger:
    platform: webhook
    webhook_id: hassalarm-webhook-2323
  action:
    service: input_datetime.set_datetime
    data_template:
      entity_id: "{{ trigger.json.entity_id }}"
      datetime: "{{ trigger.json.datetime }}"
```

The app reports "Published Successfully" and correctly shows what the next scheduled alarm is.

Any ideas? Thanks!

**Comment by Johboh** [comment]
Hey!
I think your webhook should be:
```
- id: 'hassalarm'
  alias: Webhook for Hassalarm
  trigger:
    platform: webhook
    webhook_id: hassalarm-webhook-2323
  action:
    service: input_datetime.set_datetime
    data_template:
      entity_id: "{{ trigger.json.entity_id }}"
      timestamp: "{{ trigger.json.timestamp}}"
```
E.g. `timestamp` instead of `datetime`, as that is what is published from the app (if you check the app logs).
Also, what version of Home Assistant are you using?

**Comment by Johboh** [comment]
Or maybe even:
```
- id: 'hassalarm'
  alias: Webhook for Hassalarm
  trigger:
    platform: webhook
    webhook_id: hassalarm-webhook-2323
  action:
    service: input_datetime.set_datetime
    data_template:
      entity_id: "{{ trigger.json.entity_id }}"
      timestamp: {{ trigger.json.timestamp}}
```
